// THis will tell where to place the timer bar
export const TIMER_BAR_POSITION_TYPE = Object.freeze({
  EVERY_PAGE: "EVERY_PAGE",
  ONLY_HOME_PAGE: "ONLY_HOME_PAGE",
  ALL_PRODUCT_PAGE: "ALL_PRODUCT_PAGE",
  SPECIFIC_PRODUCT_PAGES: "SPECIFIC_PRODUCT_PAGES",
  ALL_COLLECTIONS: "ALL_COLLECTIONS",
  SPECIFIC_COLLECTIONS: "SPECIFIC_COLLECTIONS",
});
