const themesArray = {
  Custom: {
    titleColor: "000000",
    subheadingColor: "000000",
    clockTimerColor: "000000",
    clockTimerDisc: "000000",
    clockSingleColorBackground: "FFFFFF",
    backgroundColorType: "single", // TODO change to enums
    clockGradientColor1: "DDDDDD",
    clockGradientColor2: "FFFFFF",
    legendColor: "000000",
    borderColor: "000000",
    gradientAngle: "45",
    fontFamily: "",
  },
  Dawn: {
    titleColor: "ceccdc",
    subheadingColor: "9f9daa",
    clockTimerColor: "ff3e20",
    legendColor: "9f9daa",
    clockSingleColorBackground: "FFFFFF",
    backgroundColorType: "gradient",
    clockGradientColor1: "252237",
    clockGradientColor2: "4c4861",
    borderColor: "000000",
    gradientAngle: "45",
    fontFamily: "",
  },

  Electric: {
    titleColor: "192c6b",
    subheadingColor: "192c6b",
    clockTimerColor: "ffffff",
    clockSingleColorBackground: "FFFFFF",
    backgroundColorType: "gradient",
    clockGradientColor1: "00ffee",
    clockGradientColor2: "d285ff",
    legendColor: "ddebf4",
    borderColor: "000000",
    gradientAngle: "153",
    fontFamily: "",
  },
  DarkNos: {
    titleColor: "ffffff",
    subheadingColor: "767676",
    clockTimerColor: "ffc713",
    clockSingleColorBackground: "7FB2F0",
    backgroundColorType: "gradient",
    clockGradientColor1: "000000",
    clockGradientColor2: "000000",
    legendColor: "ddebf4",
    borderColor: "000000",
    gradientAngle: "153",
    fontFamily: "",
  },
  Whimsical_Wisteria: {
    titleColor: "ffffff",
    subheadingColor: "000000",
    clockTimerColor: "fcf808",
    clockSingleColorBackground: "000000",
    backgroundColorType: "gradient",
    clockGradientColor1: "654ea3",
    clockGradientColor2: "eaafc8",
    legendColor: "ddebf4",
    borderColor: "000000",
    gradientAngle: "13",
    fontFamily: "",
  },

  Summer_Hues: {
    titleColor: "ffffff",
    subheadingColor: "000000",
    clockTimerColor: "1A1A4C",
    clockSingleColorBackground: "000000",
    backgroundColorType: "gradient",
    clockGradientColor1: "22c1c3",
    clockGradientColor2: "fdbb2d",
    legendColor: "ddebf4",
    borderColor: "000000",
    gradientAngle: "13",
    fontFamily: "",
  },

  Sunset_Serenade: {
    titleColor: "ffffff",
    subheadingColor: "000000",
    clockTimerColor: "1A1A4C",
    clockSingleColorBackground: "000000",
    backgroundColorType: "gradient",
    clockGradientColor1: "FEE140",
    clockGradientColor2: "FA709A",
    legendColor: "ddebf4",
    borderColor: "000000",
    gradientAngle: "13",
    fontFamily: "",
  },

  Sunny_Tangerine: {
    titleColor: "ffffff",
    subheadingColor: "000000",
    clockTimerColor: "ffffff",
    clockSingleColorBackground: "FEE140",
    backgroundColorType: "gradient",
    clockGradientColor1: "e96443",
    clockGradientColor2: "904e95",
    legendColor: "ddebf4",
    borderColor: "000000",
    gradientAngle: "90",
    fontFamily: "",
  },
};

export const timerBarThemesArray = {
  Custom: {
    titleColor: "000000",
    subheadingColor: "000000",
    clockTimerColor: "000000",
    clockTimerDisc: "000000",
    clockSingleColorBackground: "FFFFFF",
    backgroundColorType: "single", // TODO change to enums
    clockGradientColor1: "DDDDDD",
    clockGradientColor2: "FFFFFF",
    legendColor: "000000",
    borderColor: "000000",
    gradientAngle: "45",
    fontFamily: "",
    buttonColor: "000000",
    buttonFontSize: "14",
    buttonFontColor: "ffffff",
    closeIconColor: "000000",
  },
  Dawn: {
    titleColor: "ceccdc",
    subheadingColor: "9f9daa",
    clockTimerColor: "ff3e20",
    legendColor: "9f9daa",
    clockSingleColorBackground: "FFFFFF",
    backgroundColorType: "gradient",
    clockGradientColor1: "252237",
    clockGradientColor2: "4c4861",
    borderColor: "000000",
    gradientAngle: "45",
    fontFamily: "",
    buttonColor: "000000",
    buttonFontSize: "14",
    buttonFontColor: "ffffff",
    closeIconColor: "000000",
  },

  Electric: {
    titleColor: "192c6b",
    subheadingColor: "192c6b",
    clockTimerColor: "ffffff",
    clockSingleColorBackground: "FFFFFF",
    backgroundColorType: "gradient",
    clockGradientColor1: "00ffee",
    clockGradientColor2: "d285ff",
    legendColor: "ddebf4",
    borderColor: "000000",
    gradientAngle: "153",
    fontFamily: "",
    buttonColor: "000000",
    buttonFontSize: "14",
    buttonFontColor: "ffffff",
    closeIconColor: "000000",
  },
  DarkNos: {
    titleColor: "ffffff",
    subheadingColor: "767676",
    clockTimerColor: "ffc713",
    clockSingleColorBackground: "7FB2F0",
    backgroundColorType: "gradient",
    clockGradientColor1: "000000",
    clockGradientColor2: "000000",
    legendColor: "ddebf4",
    borderColor: "000000",
    gradientAngle: "153",
    fontFamily: "",
    buttonColor: "000000",
    buttonFontSize: "14",
    buttonFontColor: "ffffff",
    closeIconColor: "000000",
  },
  Whimsical_Wisteria: {
    titleColor: "ffffff",
    subheadingColor: "000000",
    clockTimerColor: "fcf808",
    clockSingleColorBackground: "000000",
    backgroundColorType: "gradient",
    clockGradientColor1: "654ea3",
    clockGradientColor2: "eaafc8",
    legendColor: "ddebf4",
    borderColor: "000000",
    gradientAngle: "13",
    fontFamily: "",
    buttonColor: "000000",
    buttonFontSize: "14",
    buttonFontColor: "ffffff",
    closeIconColor: "000000",
  },

  Summer_Hues: {
    titleColor: "ffffff",
    subheadingColor: "000000",
    clockTimerColor: "1A1A4C",
    clockSingleColorBackground: "000000",
    backgroundColorType: "gradient",
    clockGradientColor1: "22c1c3",
    clockGradientColor2: "fdbb2d",
    legendColor: "ddebf4",
    borderColor: "000000",
    gradientAngle: "13",
    fontFamily: "",
    buttonColor: "000000",
    buttonFontSize: "14",
    buttonFontColor: "ffffff",
    closeIconColor: "000000",
  },

  Sunset_Serenade: {
    titleColor: "ffffff",
    subheadingColor: "000000",
    clockTimerColor: "1A1A4C",
    clockSingleColorBackground: "000000",
    backgroundColorType: "gradient",
    clockGradientColor1: "FEE140",
    clockGradientColor2: "FA709A",
    legendColor: "ddebf4",
    borderColor: "000000",
    gradientAngle: "13",
    fontFamily: "",
    buttonColor: "000000",
    buttonFontSize: "14",
    buttonFontColor: "ffffff",
    closeIconColor: "000000",
  },

  Sunny_Tangerine: {
    titleColor: "ffffff",
    subheadingColor: "000000",
    clockTimerColor: "ffffff",
    clockSingleColorBackground: "FEE140",
    backgroundColorType: "gradient",
    clockGradientColor1: "e96443",
    clockGradientColor2: "904e95",
    legendColor: "ddebf4",
    borderColor: "000000",
    gradientAngle: "90",
    fontFamily: "",
    buttonColor: "000000",
    buttonFontSize: "14",
    buttonFontColor: "ffffff",
    closeIconColor: "000000",
  },
};

export const templateOptionsList = [
  { label: "Custom", value: "Custom" },
  { label: "Dawn", value: "Dawn" },
  { label: "Electric", value: "Electric" },
  { label: "DarkNos", value: "DarkNos" },
  { label: "Whimsical Wisteria", value: "Whimsical_Wisteria" },
  { label: "Summer Vibe", value: "Summer_Hues" },
  { label: "Sunset Serenade", value: "Sunset_Serenade" },
  { label: "Sunny Tangerine", value: "Sunny_Tangerine" },
];

export const defaultSpacingAndSizing = {
  paddingTop: 30,
  paddingBottom: 30,
  marginTop: 20,
  marginBottom: 20,
  titleSize: 28,
  subHeadingSize: 16,
  timerSize: 40,
  legendSize: 14,
  cornerRadius: 8,
  borderSize: 0,
};

export const defaultTimerBarSpacingAndSizing = {
  paddingTop: 10,
  paddingBottom: 10,
  marginTop: 20,
  marginBottom: 20,
  titleSize: 18,
  subHeadingSize: 14,
  timerSize: 22,
  legendSize: 10,
  cornerRadius: 4,
  borderSize: 0,
};

export default themesArray;
